name: foyer
channels:
  - conda-forge
  - omnia
dependencies:
  - lark-parser
  - lxml
  - networkx>=2.5
  - openmm>=7.6
  - parmed
  - ele
  - requests
  - pip
  - pytest
  - pytest-azurepipelines
  - pytest-cov
  - pytest-timeout
  - python<=3.8
