name: foyer
channels:
  - conda-forge
  - omnia
dependencies:
  - lark-parser
  - lxml
  - networkx>=2.5
  - openmm
  - parmed>=3.4.3
  - ele
  - requests
  - pip
  - pytest
  - pytest-azurepipelines
  - pytest-cov
  - pytest-timeout
  - pytest-xdist
  - python>=3.9
