name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  schedule:
    - cron:  "0 0 * * *"

jobs:
  test:
    if: github.event.pull_request.draft == false
    name: Foyer Tests (python)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.13"]

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v4
        name: Checkout Branch / Pull Request

      - name: Install Mamba (Linux)
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: environment-dev.yml
          create-args: python=${{ matrix.python-version }}

      - name: Install Package
        run: python -m pip install -e .

      - name: Test (OS -> ${{ matrix.os }} / Python -> ${{ matrix.python-version }})
        run: python -m pytest -v --cov=foyer --cov-report=xml --cov-append --cov-config=setup.cfg --color yes --pyargs foyer

      - name: Upload Coverage Report
        uses: codecov/codecov-action@v5
        with:
          name: Foyer-Coverage
          verbose: true
          files: ./coverage.xml

  arch-test:
    if: github.event.pull_request.draft == false
    name: Foyer Tests (arch)
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.13"]

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v4
        name: Checkout Branch / Pull Request

      - name: Install Mamba (Linux)
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: environment-dev.yml
          create-args: python=${{ matrix.python-version }}

      - name: Install Package
        run: python -m pip install -e .

      - name: Test (OS -> ${{ matrix.os }} / Python -> ${{ matrix.python-version }})
        run: python -m pytest -v --color yes --pyargs foyer
